### ISSUE TITLE
Amethyst Equipment [Fabric] [1.18.1]

### ISSUE THREAD

**Issue by xanthian** [jexline/exline-mods-issues#13]
[Render thread/ERROR] (Minecraft) Parsing error loading recipe amethystequipment:amethyst_hammer_recipe
 com.google.gson.JsonSyntaxException: Unknown item 'hammermod:hammer_amethyst'
	at net.minecraft.recipe.ShapedRecipe.method_17878(ShapedRecipe.java:253) ~[minecraft-project-@-merged-named.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.recipe.ShapedRecipe.getItem(ShapedRecipe.java:253) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.recipe.ShapedRecipe.outputFromJson(ShapedRecipe.java:240) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.recipe.ShapedRecipe$Serializer.read(ShapedRecipe.java:273) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.recipe.ShapedRecipe$Serializer.read(ShapedRecipe.java:260) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.recipe.RecipeManager.deserialize(RecipeManager.java:126) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager.java:55) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager.java:34) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader.java:13) ~[minecraft-project-@-merged-named.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload.java:71) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:151) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:125) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:134) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.createIntegratedResourceManager(MinecraftClient.java:2154) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient.java:2003) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient.java:1943) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$Entry.start(WorldListWidget.java:436) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$Entry.play(WorldListWidget.java:342) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$Entry.mouseClicked(WorldListWidget.java:273) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.widget.EntryListWidget.mouseClicked(EntryListWidget.java:359) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement.java:27) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.Mouse.method_1611(Mouse.java:94) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:491) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:94) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.Mouse.method_22686(Mouse.java:165) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:101) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.Mouse.method_22684(Mouse.java:165) ~[minecraft-project-@-merged-named.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:220) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1145) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:733) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [minecraft-project-@-merged-named.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]

**Comment by jexline** [comment]
this is not a game breaking error and is intentional. If you have the War Hammer mod installed it unlocks a new hammer recipe.

**Comment by xanthian** [comment]
although not game breaking, its unnecessary console spam and not good practice.
