### ISSUE TITLE
door placement crash in 1.19.4

### ISSUE THREAD

**Issue by wyrdde** [jexline/exline-mods-issues#37]
https://crashy.net/3d5b8a83-74cd-42db-9fde-4b9edcc22839

Received the above error post-crash (twice today)—I tried to place a "Spruce Glass Wall" [**Exline's Doors**] atop a "Spruce Pillar Trim" [**Handcrafted** - [mod link](https://www.curseforge.com/minecraft/mc-mods/handcrafted) ] while flying/ levitating (in creative mode). No problem performing the same action with my feet on the floor/ ground.

p.s. Your awnings & doors are among my must-have mods; they look especially good alongside pieces from Handcrafted & various of Macaw's mods!

**Comment by rsdworker** [comment]
i had same issue but its was window panel which i crashed - the doors didnt crash for me

```
---- Minecraft Crash Report ----
// There are four lights!

Time: 2023-05-17 13:39:47
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot set property class_2753{name=facing, clazz=class net.minecraft.class_2350, values=[north, south, west, east]} to down on Block{exlinedoors:spruce_glass_wall}, it is not an allowed value
	at net.minecraft.class_2688.method_11657(class_2688.java:130)
	at com.exline.exlinedoors.block.ModFrameBlock.method_9605(ModFrameBlock.java:76)
	at net.minecraft.class_1747.method_7707(class_1747.java:123)
	at net.minecraft.class_1747.method_7712(class_1747.java:75)
	at net.minecraft.class_1747.method_7884(class_1747.java:50)
	at net.minecraft.class_1799.method_7981(class_1799.java:274)
	at net.minecraft.class_636.method_41934(class_636.java:367)
	at net.minecraft.class_636.method_41933(class_636.java:328)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:327)
	at net.minecraft.class_310.method_1583(class_310.java:1799)
	at net.minecraft.class_310.method_1508(class_310.java:2053)
	at net.minecraft.class_310.method_1574(class_310.java:1880)
	at net.minecraft.class_310.method_1523(class_310.java:1180)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2688.method_11657(class_2688.java:130)
	at com.exline.exlinedoors.block.ModFrameBlock.method_9605(ModFrameBlock.java:76)
	at net.minecraft.class_1747.method_7707(class_1747.java:123)
	at net.minecraft.class_1747.method_7712(class_1747.java:75)
	at net.minecraft.class_1747.method_7884(class_1747.java:50)
	at net.minecraft.class_1799.method_7981(class_1799.java:274)
	at net.minecraft.class_636.method_41934(class_636.java:367)
	at net.minecraft.class_636.method_41933(class_636.java:328)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:327)
	at net.minecraft.class_310.method_1583(class_310.java:1799)
	at net.minecraft.class_310.method_1508(class_310.java:2053)

-- Affected level --
Details:
	All players: 1 total; [class_746['rsdworker'/11, l='ClientLevel', x=350.71, y=200.00, z=318.10]]
	Chunk stats: 1225, 809
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,200,0), Section: (at 0,8,0 in 0,12,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 14270 game time, 14270 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:825)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2151994008 bytes (2052 MiB) / 4284481536 bytes (4086 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 3.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 750 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1380
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1694
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 22678.76
	Virtual memory used (MB): 17311.61
	Swap memory total (MB): 14526.79
	Swap memory used (MB): 2072.35
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		brrp_v1: Better Runtime Resource Pack (BRRP) v1 1.0.0
		exlineawnings: Exline's Awnings Mod 1.1.5
		exlinedoors: Exline's Doors 2.3.8
		exlinefurniture: Exline's Furniture 2.3.5
		fabric-api: Fabric API 0.80.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.25+504944c8f4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.26+504944c8f4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.8+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.7+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.35+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.16+504944c8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.28+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.7+504944c8f4
			fabric-commands-v0: Fabric Commands (v0) 0.2.45+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.55+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.10+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.4.2+9a7c5daaf4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.16+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.4.1+504944c8f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.46+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.14+504944c8f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.5.0+76ba65ebf4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.53+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.34+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.18+504944c8f4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.6+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.34+504944c8f4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.32+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.16+504944c8f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.28+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.32+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.2+504944c8f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.40+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.31+504944c8f4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.2+504944c8f4
			fabric-networking-v0: Fabric Networking (v0) 0.3.42+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.4+504944c8f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.24+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.9+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.1+504944c8f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.6+504944c8f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.1.2+81e8c576f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.39+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.29+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.22+504944c8f4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.42+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.2+504944c8f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.2+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.3+1e1fb126f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.46+504944c8f4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.21+504944c8f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.10+504944c8f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.1.2+504944c8f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.0.4+504944c8f4
		fabricloader: Fabric Loader 0.14.19
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.7
			journeymap-api-fabric: JourneyMap API 1.19.4-1.9-fabric-SNAPSHOT
		jsblock: Joban Client Mod 1.2.1-hotfix-1+mc1.19.4
		londonunderground: MTR London Underground Addon 1.19.4-3.2.0-1.11
		minecraft: Minecraft 1.19.4
		mishanguc: Mishang Urban Construction 1.2.1
		msd: MTR Station Decoration Addon 1.19.4-3.2.0-1.3.4
		mtr: Minecraft Transit Railway 1.19.4-3.2.2-hotfix-1
		mtrsteamloco: Nemo's Transit Expansion 1.19.4-0.3.2
		worldedit: WorldEdit 7.2.14+6360-094b734
		worldeditcui: WorldEditCUI 1.19.4+01
	Launched Version: fabric-loader-0.14.19-1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 516.94, NVIDIA Corporation
	Window size: 1920x1057
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: en_us
	CPU: 4x Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['rsdworker'/11, l='ServerLevel[husky world]', x=350.71, y=200.00, z=318.10]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable``
```

**Comment by jexline** [comment]
Thank you, I am sorry I didnt catch this before i uploaded it. Ill work on fixing it right away,

**Comment by jexline** [comment]
I believe I found the problem. I was using 'getPlayerLookDirection' when I needed to use 'getHorizontalPlayerFacing' I will upload a new file soon!
